version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5433/crawler_db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crawler_db

volumes:
  postgres_data: 